### ISSUE TITLE
MappingModeler et KG creator probleme avec le module d'upload après l'ajout d'un csv (tentative avortée de reinitialisation?)

### ISSUE THREAD

**Issue by claudefauconnet** [souslesens/souslesensVocables#1008]

**Comment by ounnoughikarim** [comment]
![Image](https://github.com/user-attachments/assets/56fab98a-74a3-4f54-bbfd-e5cd015e3e9c)
Uncaught Error: Minified React error #299; visit https://reactjs.org/docs/error-decoder.html?invariant=299 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Je.createRoot (client-2d560354.js:61:55586)
    at window.MappingModeler.createApp (mappingModeler_upload_app.js:1:2093)
    at HTMLDivElement.open (mappingModeler.js:60:47)
    at $.<computed>.<computed>._trigger (jquery-ui.js:697:13)
    at $.<computed>.<computed>.open (jquery-ui.js:12215:8)
    at $.<computed>.<computed>.open (jquery-ui.js:144:25)
    at HTMLDivElement.<anonymous> (jquery-ui.js:256:40)
    at Function.each (jquery-1.12.4.js:370:19)
    at jQuery.fn.init.each (jquery-1.12.4.js:137:17)
    at $.fn.<computed> [as dialog] (jquery-ui.js:236:10)
    at HTMLDivElement.<anonymous> (lineage_createRelation.js:18:34)
    at HTMLDivElement.<anonymous> (jquery-1.12.4.js:10641:14)
    at Function.each (jquery-1.12.4.js:370:19)
    at jQuery.fn.init.each (jquery-1.12.4.js:137:17)
    at Object.<anonymous> (jquery-1.12.4.js:10640:9)
    at fire (jquery-1.12.4.js:3232:31)
    at Object.fireWith [as resolveWith] (jquery-1.12.4.js:3362:7)
    at done (jquery-1.12.4.js:9840:14)
    at XMLHttpRequest.callback (jquery-1.12.4.js:10311:8)

**Comment by ounnoughikarim** [comment]
Se produit au chargement d'un fichier CSV dans mappingModeler mais n'apparait pas à chaque fois
